spring.application.name=eventbooking

spring.data.mongodb.uri=mongodb://eventbooking_user:abc123@localhost:27017/eventbooking?authSource=eventbooking

spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.boot.context.properties=TRACE