spring.application.name=eventbooking

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=eventbooking
spring.data.mongodb.username=eventbooking_user
spring.data.mongodb.password=abc123
spring.data.mongodb.authentication-database=eventbooking

spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.boot.context.properties=TRACE